export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const GET_USER = "GET_USER";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const REFRESHING_TOKEN = "REFRESHING_TOKEN";
export const REFRESHED_TOKEN = "REFRESHED_TOKEN";
