export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORGANIZATIONS_PATIENT = "GET_ORGANIZATIONS_PATIENT";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_PRIMARY_NOTIFICATIONS = "GET_PRIMARY_NOTIFICATIONS";
export const GET_ALL_ORG_PATIENT = "GET_ALL_ORG_PATIENT";